export const ADD_TODO = 'ADD_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const REMOVE_TODO = 'REMOVE_TODO'
export const TOGGLE_TAG = 'TOGGLE_TAG'
export const TOGGLE_TODO_TAG = 'TOGGLE_TODO_TAG'
export const CHANGE_TODO_ID = 'CHANGE_TODO_ID'
export const CONTENT_EDIT = 'CONTENT_EDIT'